baseurl: "/" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "d4mianwayne.github.io" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: Batcave - Infosec Blog
header: Reverse Engineering is my passion, cracks CTFs for breakfast, and protects Gotham as a side quest.

# for welcome page
# to replace image go to index.html
email:
  address: "dubeyayushmanrobin@gmail.com"


# google analytics
google:
    tracking-id: "UA-144686323-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
